# Generated by Django 5.1.4 on 2026-09-01 08:26

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land'), ('INDUSTRIAL', 'Industrial')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_property_type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('UNDER_CONSTRUCTION', 'Under construction'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developed_projects', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_project',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('number_of_floors', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='inventory.project')),
            ],
            options={
                'db_table': 'inventory_building',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_multi_unit', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('UNDER_MAINTENANCE', 'Under maintenance'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='inventory.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='inventory.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='inventory.propertytype')),
            ],
            options={
                'db_table': 'inventory_property',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(max_length=50)),
                ('listing_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent'), ('SALE_AND_RENT', 'Sale and rent')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_OFFER', 'Under offer'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('OFF_MARKET', 'Off market'), ('EXPIRED', 'Expired')], max_length=20)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.property')),
            ],
            options={
                'db_table': 'inventory_listing',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('OCCUPIED', 'Occupied'), ('UNDER_MAINTENANCE', 'Under maintenance'), ('OFF_MARKET', 'Off market')], max_length=20)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.property')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.propertytype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_unit',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.unit')),
            ],
            options={
                'db_table': 'inventory_property_status_history',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('FLOOR_PLAN', 'Floor plan'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('VIRTUAL_TOUR', 'Virtual tour')], max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.listing')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.unit')),
            ],
            options={
                'db_table': 'inventory_media',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.unit'),
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to='contacts.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='inventory.property')),
            ],
            options={
                'db_table': 'inventory_property_owner',
                'constraints': [models.CheckConstraint(condition=models.Q(('ownership_percentage__gt', 0), ('ownership_percentage__lte', 100)), name='inventory_property_owner_pct_range')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['amenities'], name='inventory_property_amen_gin'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='inventory_property_cust_gin'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('property', 'unit_number'), name='inventory_unit_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='propertystatushistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('unit__isnull', True)), models.Q(('property__isnull', True), ('unit__isnull', False)), _connector='OR'), name='inventory_status_history_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('property__isnull', False), ('unit__isnull', False), ('listing__isnull', False), _connector='OR'), name='inventory_media_has_target'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('storage_key__isnull', False)), name='inventory_media_has_blob_ref'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('reference_code',), name='inventory_listing_reference_uniq'),
        ),
    ]
