# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='media',
            name='inventory_media_has_blob_ref',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_media', to='collaboration.file'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('file__isnull', False), ('storage_key__isnull', False), _connector='OR'), name='inventory_media_has_blob_ref'),
        ),
    ]
