# Generated by Django 5.1.4 on 2026-09-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_media_inventory_media_has_blob_ref_media_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='co_listing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_listed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='mandate_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='mandate_type',
            field=models.CharField(blank=True, choices=[('EXCLUSIVE', 'Exclusive'), ('OPEN', 'Open / shared'), ('SOLE_SELLING', 'Sole selling rights')], max_length=20, null=True),
        ),
    ]
