# Generated by Django 5.1.4 on 2026-09-18 05:36

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_listing_co_listing_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='inventory_listing_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference_code'], name='inventory_listing_ref_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='inventory_property_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address_line_1'], name='inventory_property_addr_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['city'], name='inventory_property_city_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
