# Generated by Django 5.1.4 on 2026-09-18 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_listing_inventory_listing_title_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('co_listing_agent', models.F('assigned_agent')), _negated=True), name='inventory_listing_colist_distinct'),
        ),
    ]
