# Generated by Django 5.1.4 on 2026-09-01 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('current_value', models.BigIntegerField(default=0)),
                ('padding', models.IntegerField(default=6)),
            ],
            options={
                'db_table': 'core_sequence',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('CONTACT', 'Contact'), ('LEAD', 'Lead'), ('DEAL', 'Deal'), ('PROPERTY', 'Property'), ('LISTING', 'Listing'), ('LEASE', 'Lease')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_custom_field',
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'key'), name='core_custom_field_entity_key_uniq')],
            },
        ),
    ]
