"""Public write API for `core` (architecture.md §1.2).

Abstract bases, custom-field registry, reference-code sequences.

This is the ONLY module another app may import to mutate `core`-owned rows. Calling
`Model.objects.create/update/delete` on a `core` model from another app is a forbidden
pattern, as is reacting to `post_save` signals to do it.
"""
from django.db import transaction

from .models import Sequence


@transaction.atomic
def next_reference(key, *, prefix=None, padding=6):
    """The next code in the `key` series — e.g. `next_reference("listing", prefix="LST")`.

    architecture.md §2: human-readable sequential identifiers "MUST be generated by a
    concurrency-safe mechanism — a dedicated Postgres sequence per series, or a
    `core_sequence` counter row updated via `SELECT ... FOR UPDATE` inside the creating
    transaction — never by `MAX()+1` or app-side counting, which race under load."

    `MAX()+1` is not merely theoretically racy here: two agents publishing a listing in the
    same second both read the same maximum, and the loser hits the partial unique index on
    `reference_code` — a 500 on a perfectly valid action. `SELECT ... FOR UPDATE` makes the
    second transaction wait for the first to commit.

    Runs inside the caller's transaction when there is one, so a code is never consumed by a
    creation that then rolls back. That is also why this must not be moved to its own
    connection or an autonomous transaction.
    """
    row, _ = Sequence.objects.get_or_create(
        key=key, defaults={"prefix": prefix, "padding": padding}
    )
    # Re-read under a row lock. get_or_create's returned instance carries the value from
    # before the lock, which is exactly the read two racing callers would share.
    row = Sequence.objects.select_for_update().get(pk=row.pk)
    row.current_value += 1
    row.save(update_fields=["current_value"])

    body = str(row.current_value).zfill(row.padding)
    return f"{row.prefix}-{body}" if row.prefix else body
