"""Public write API for `core` (architecture.md §1.2).

Abstract bases, custom-field registry, reference-code sequences.

This is the ONLY module another app may import to mutate `core`-owned rows. Calling
`Model.objects.create/update/delete` on a `core` model from another app is a forbidden
pattern, as is reacting to `post_save` signals to do it.
"""
from django.db import transaction

from .models import Sequence


@transaction.atomic
def next_reference(key, *, prefix=None, padding=6):
    """The next code in the `key` series — e.g. `next_reference("listing", prefix="LST")`.

    architecture.md §2: human-readable sequential identifiers "MUST be generated by a
    concurrency-safe mechanism — a dedicated Postgres sequence per series, or a
    `core_sequence` counter row updated via `SELECT ... FOR UPDATE` inside the creating
    transaction — never by `MAX()+1` or app-side counting, which race under load."

    `MAX()+1` is not merely theoretically racy here: two agents publishing a listing in the
    same second both read the same maximum, and the loser hits the partial unique index on
    `reference_code` — a 500 on a perfectly valid action. `SELECT ... FOR UPDATE` makes the
    second transaction wait for the first to commit.

    Runs inside the caller's transaction when there is one, so a code is never consumed by a
    creation that then rolls back. That is also why this must not be moved to its own
    connection or an autonomous transaction.
    """
    row, _ = Sequence.objects.get_or_create(
        key=key, defaults={"prefix": prefix, "padding": padding}
    )
    # Re-read under a row lock. get_or_create's returned instance carries the value from
    # before the lock, which is exactly the read two racing callers would share.
    row = Sequence.objects.select_for_update().get(pk=row.pk)
    row.current_value += 1
    row.save(update_fields=["current_value"])

    body = str(row.current_value).zfill(row.padding)
    return f"{row.prefix}-{body}" if row.prefix else body


def validate_custom_data(entity_type, data, *, partial=False):
    """Validate an entity's ``custom_data`` against the CustomField registry (SRS 3.17.4).

    Lenient by default — an EMPTY registry (today's state) validates everything, so the
    call sites cost nothing until an admin registers fields. Unknown keys are refused only
    under ``CUSTOM_FIELD_STRICT=True``: years of ad-hoc JSON may predate the registry, and
    strictness is an opt-in migration, not a surprise.

    ``partial`` skips required-field checks — a PATCH that doesn't mention a required key
    is not removing it.
    """
    from django.conf import settings
    from django.core.exceptions import ValidationError

    from .models import CustomField

    data = data or {}
    fields = {
        field.key: field
        for field in CustomField.objects.filter(entity_type=entity_type, is_active=True)
    }
    errors = {}

    if getattr(settings, "CUSTOM_FIELD_STRICT", False):
        for key in set(data) - set(fields):
            errors[key] = "Unknown custom field."

    for key, field in fields.items():
        if key not in data:
            if field.is_required and not partial:
                errors[key] = "This custom field is required."
            continue
        value = data[key]
        if value is None:
            if field.is_required:
                errors[key] = "This custom field is required."
            continue
        kind = field.data_type
        if kind == "TEXT" and not isinstance(value, str):
            errors[key] = "Expected text."
        elif kind == "NUMBER" and (
            isinstance(value, bool) or not isinstance(value, (int, float))
        ):
            errors[key] = "Expected a number."
        elif kind == "BOOLEAN" and not isinstance(value, bool):
            errors[key] = "Expected true or false."
        elif kind == "DATE":
            import datetime

            if not isinstance(value, str):
                errors[key] = "Expected an ISO date."
            else:
                try:
                    datetime.date.fromisoformat(value)
                except ValueError:
                    errors[key] = "Expected an ISO date."
        elif kind == "SINGLE_SELECT":
            options = field.choices or []
            if value not in options:
                errors[key] = f"Pick one of {options}."
        elif kind == "MULTI_SELECT":
            options = field.choices or []
            if not isinstance(value, list) or any(v not in options for v in value):
                errors[key] = f"Pick from {options}."

    if errors:
        raise ValidationError(errors)
    return data
