# Generated by Django 5.1.4 on 2026-09-01 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('PROPERTY_FINDER', 'Property Finder'), ('BAYUT', 'Bayut'), ('DUBIZZLE', 'Dubizzle'), ('MLS', 'MLS'), ('GOOGLE', 'Google'), ('OUTLOOK', 'Outlook'), ('WHATSAPP', 'WhatsApp'), ('TWILIO', 'Twilio'), ('MAILGUN', 'Mailgun'), ('DOCUSIGN', 'DocuSign'), ('WEBHOOK', 'Webhook'), ('OTHER', 'Other')], max_length=30)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('BIDIRECTIONAL', 'Bidirectional')], max_length=20)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'API key'), ('OAUTH2', 'OAuth2'), ('BASIC', 'Basic'), ('NONE', 'None')], max_length=20)),
                ('credentials_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_connection',
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('KPI_DAILY', 'Daily KPIs'), ('PIPELINE', 'Pipeline'), ('LEADERBOARD', 'Leaderboard'), ('FINANCE_SUMMARY', 'Finance summary')], max_length=30)),
                ('scope_type', models.CharField(choices=[('ORG', 'Organization'), ('BRANCH', 'Branch'), ('TEAM', 'Team'), ('USER', 'User')], max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('as_of_date', models.DateField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_dashboard_snapshot',
                'constraints': [models.UniqueConstraint(fields=('snapshot_type', 'scope_type', 'scope_id', 'as_of_date'), name='platform_dashboard_snapshot_uniq', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales'), ('LEADS', 'Leads'), ('LISTINGS', 'Listings'), ('FINANCE', 'Finance'), ('LEASING', 'Leasing'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('CUSTOM', 'Custom')], max_length=20)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team'), ('BRANCH', 'Branch'), ('ORG', 'Organization')], default='PRIVATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_saved_report',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('next_run_at', models.DateTimeField()),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX'), ('CSV', 'CSV')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='platform.savedreport')),
            ],
            options={
                'db_table': 'platform_report_schedule',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='platform.connection')),
            ],
            options={
                'db_table': 'platform_sync_log',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('PAYMENT_POSTED', 'Payment posted'), ('COMMISSION_APPROVED', 'Commission approved')], max_length=30)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_audit_event',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='platform_audit_entity_idx'), models.Index(fields=['actor_user', '-created_at'], name='platform_audit_actor_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('local_id', models.UUIDField()),
                ('external_id', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='platform.connection')),
            ],
            options={
                'db_table': 'platform_external_mapping',
                'constraints': [models.UniqueConstraint(fields=('connection', 'entity_type', 'local_id'), name='platform_mapping_local_uniq'), models.UniqueConstraint(fields=('connection', 'entity_type', 'external_id'), name='platform_mapping_external_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('target_url', models.URLField(blank=True, max_length=500, null=True)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='platform.connection')),
            ],
            options={
                'db_table': 'platform_webhook',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('direction', 'OUTBOUND'), _negated=True), ('target_url__isnull', False), _connector='OR'), name='platform_webhook_outbound_has_target')],
            },
        ),
    ]
