# Generated by Django 5.1.4 on 2026-09-01 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts_contact',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone'), ('MARKETING', 'Marketing')], max_length=20)),
                ('status', models.CharField(choices=[('OPTED_IN', 'Opted in'), ('OPTED_OUT', 'Opted out'), ('PENDING', 'Pending')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_consent',
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('SPOUSE', 'Spouse'), ('FAMILY_MEMBER', 'Family member'), ('COMPANY_REPRESENTATIVE', 'Company representative'), ('LEGAL_REPRESENTATIVE', 'Legal representative'), ('REFERRAL_SOURCE', 'Referral source'), ('PROPERTY_OWNER', 'Property owner')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='contacts.contact')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_relationship',
            },
        ),
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('INVESTOR', 'Investor'), ('VENDOR', 'Vendor'), ('DEVELOPER', 'Developer'), ('REFERRAL_PARTNER', 'Referral partner'), ('LEGAL_REPRESENTATIVE', 'Legal representative'), ('OTHER', 'Other')], max_length=25)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_role',
                'constraints': [models.UniqueConstraint(fields=('contact', 'role'), name='contacts_contact_role_uniq')],
            },
        ),
    ]
