# Generated by Django 5.1.4 on 2026-09-18 05:36

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_default_source'),
        ('crm', '0003_campaignstep_template_closingchecklistitem_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='contacts_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='contacts_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['company_name'], name='contacts_company_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='contacts_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone'], name='contacts_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
