# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('finance', '0002_account_entry_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='collaboration.document'),
        ),
        migrations.AddField(
            model_name='ownerstatement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_statements', to='collaboration.document'),
        ),
    ]
