# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_default_source'),
        ('crm', '0002_agent_location_point_append_only'),
        ('identity', '0003_portalprofile_contact'),
        ('inventory', '0001_initial'),
        ('property_ops', '0003_rentschedule_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('TASK', 'Task'), ('CALL', 'Call'), ('MEETING', 'Meeting'), ('VIEWING', 'Viewing'), ('FOLLOW_UP', 'Follow up'), ('INSPECTION', 'Inspection'), ('REMINDER', 'Reminder')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('reminder_minutes_before', models.IntegerField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('VIEWING', 'Viewing'), ('INSPECTION', 'Inspection')], max_length=20, null=True)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='property_ops.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inventory.property')),
            ],
            options={
                'db_table': 'collaboration_activity',
            },
        ),
        migrations.CreateModel(
            name='CalendarLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('OUTLOOK', 'Outlook'), ('ICAL', 'iCal')], max_length=20)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('BIDIRECTIONAL', 'Bidirectional')], max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='collaboration.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_calendar_link',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('ID_DOCUMENT', 'ID document'), ('PROPERTY_DEED', 'Property deed'), ('LISTING_AGREEMENT', 'Listing agreement'), ('OFFER', 'Offer'), ('SALE_CONTRACT', 'Sale contract'), ('LEASE', 'Lease'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('INSPECTION_REPORT', 'Inspection report'), ('OTHER', 'Other')], max_length=30)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_document',
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('EDIT', 'Edit')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_grants', to='identity.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_grants', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='collaboration.document')),
            ],
            options={
                'db_table': 'collaboration_access_grant',
            },
        ),
        migrations.CreateModel(
            name='EsignEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('INTERNAL', 'Internal'), ('DOCUSIGN', 'DocuSign'), ('ADOBE_SIGN', 'Adobe Sign'), ('OTHER', 'Other')], max_length=20)),
                ('external_envelope_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_SIGNED', 'Partially signed'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('VOIDED', 'Voided'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esign_envelopes', to='collaboration.document')),
            ],
            options={
                'db_table': 'collaboration_esign_envelope',
            },
        ),
        migrations.CreateModel(
            name='EsignSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('signing_order', models.IntegerField(default=1)),
                ('role', models.CharField(choices=[('SIGNER', 'Signer'), ('APPROVER', 'Approver'), ('WITNESS', 'Witness'), ('CC', 'CC')], default='SIGNER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esign_signatures', to='contacts.contact')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='collaboration.esignenvelope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esign_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_esign_signer',
                'ordering': ['envelope', 'signing_order'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=127)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_file',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='collaboration.file'),
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_notes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='crm.lead')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='property_ops.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='inventory.property')),
            ],
            options={
                'db_table': 'collaboration_internal_note',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('TASK_DUE', 'Task due'), ('VIEWING_SCHEDULED', 'Viewing scheduled'), ('PAYMENT_RECEIVED', 'Payment received'), ('COMMISSION_APPROVED', 'Commission approved'), ('LEASE_EXPIRING', 'Lease expiring'), ('MAINTENANCE_UPDATE', 'Maintenance update'), ('MENTION', 'Mention'), ('SYSTEM', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=30, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SUPPRESSED_QUIET_HOURS', 'Suppressed (quiet hours)'), ('SUPPRESSED_PREFERENCE', 'Suppressed (preference)')], max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='collaboration.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_notification_dispatch_log',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('TASK_DUE', 'Task due'), ('VIEWING_SCHEDULED', 'Viewing scheduled'), ('PAYMENT_RECEIVED', 'Payment received'), ('COMMISSION_APPROVED', 'Commission approved'), ('LEASE_EXPIRING', 'Lease expiring'), ('MAINTENANCE_UPDATE', 'Maintenance update'), ('MENTION', 'Mention'), ('SYSTEM', 'System')], max_length=30)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='SignatureEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('REMINDER_SENT', 'Reminder sent')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_events', to='collaboration.esignenvelope')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_events', to='collaboration.esignsigner')),
            ],
            options={
                'db_table': 'collaboration_signature_event',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_template',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('CALL', 'Call'), ('MIXED', 'Mixed')], max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='crm.lead')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='inventory.property')),
            ],
            options={
                'db_table': 'collaboration_thread',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='contacts.contact')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='collaboration.template')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration.thread')),
            ],
            options={
                'db_table': 'collaboration_message',
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='crm.deal')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='collaboration.document')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='property_ops.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='inventory.property')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='crm.transaction')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='collaboration.message')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='collaboration.thread')),
            ],
            options={
                'db_table': 'collaboration_document_link',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('MISSED', 'Missed')], max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('CONNECTED', 'Connected'), ('NO_ANSWER', 'No answer'), ('VOICEMAIL', 'Voicemail'), ('BUSY', 'Busy'), ('FAILED', 'Failed')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='contacts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('recording_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to='collaboration.file')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='collaboration.thread')),
            ],
            options={
                'db_table': 'collaboration_call_log',
            },
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id__isnull', True), ('source_type__isnull', True)), models.Q(('source_id__isnull', False), ('source_type__isnull', False)), _connector='OR'), name='collaboration_activity_source_paired'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type__isnull', False)), fields=('source_type', 'source_id'), name='collaboration_activity_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='calendarlink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__isnull', False)), fields=('provider', 'external_event_id'), name='collaboration_calendar_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('user__isnull', False), _connector='OR'), name='collaboration_access_grant_has_grantee'),
        ),
        migrations.AddConstraint(
            model_name='esignsigner',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('user__isnull', False), _connector='OR'), name='collaboration_esign_signer_has_identity'),
        ),
        migrations.AddConstraint(
            model_name='internalnote',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('lead__isnull', False), ('deal__isnull', False), ('property__isnull', False), ('lease__isnull', False), _connector='OR'), name='collaboration_internal_note_has_target'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='collab_notif_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type'), name='collaboration_notification_pref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quiet_hours_end__isnull', True), ('quiet_hours_start__isnull', True)), models.Q(('quiet_hours_end__isnull', False), ('quiet_hours_start__isnull', False)), _connector='OR'), name='collaboration_notification_quiet_hours_paired'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id__isnull', False)), fields=('channel', 'provider_message_id'), name='collaboration_message_provider_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('property__isnull', False), ('deal__isnull', False), ('lease__isnull', False), ('transaction__isnull', False), ('thread__isnull', False), ('message__isnull', False), _connector='OR'), name='collaboration_document_link_has_target'),
        ),
    ]
