# Generated by Django 5.1.4 on 2026-09-01 08:37

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_default_source'),
        ('crm', '0002_agent_location_point_append_only'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_move_in', models.DateField(blank=True, null=True)),
                ('proposed_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('stated_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('background_check_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='NOT_STARTED', max_length=20)),
                ('credit_check_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='NOT_STARTED', max_length=20)),
                ('screening_result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CONVERTED', 'Converted')], default='SUBMITTED', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='contacts.contact')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='inventory.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='inventory.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_ops_application',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('lease_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('SHORT_TERM', 'Short term')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('management_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending signature'), ('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('RENEWED', 'Renewed'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_leases', to='contacts.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='inventory.property')),
                ('property_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_leases', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='contacts.contact')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='crm.transaction')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='inventory.unit')),
            ],
            options={
                'db_table': 'property_ops_lease',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('MOVE_IN', 'Move in'), ('MOVE_OUT', 'Move out'), ('ROUTINE', 'Routine'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('condition_summary', models.TextField(blank=True, null=True)),
                ('meter_readings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inventory.property')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='property_ops.lease')),
            ],
            options={
                'db_table': 'property_ops_inspection',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('held_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('FULLY_REFUNDED', 'Fully refunded'), ('FORFEITED', 'Forfeited')], default='HELD', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('refunded_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='property_ops.lease')),
            ],
            options={
                'db_table': 'property_ops_deposit',
            },
        ),
        migrations.CreateModel(
            name='LeaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('TENANT', 'Tenant'), ('CO_TENANT', 'Co-tenant'), ('GUARANTOR', 'Guarantor'), ('LANDLORD', 'Landlord')], max_length=20)),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_parties', to='contacts.contact')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='property_ops.lease')),
            ],
            options={
                'db_table': 'property_ops_lease_party',
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('NEGOTIATING', 'Negotiating'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PROPOSED', max_length=20)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('current_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposed_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('escalation_type', models.CharField(choices=[('NONE', 'None'), ('FIXED_AMOUNT', 'Fixed amount'), ('PERCENTAGE', 'Percentage')], default='NONE', max_length=20)),
                ('escalation_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_lease', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewed_from', to='property_ops.lease')),
                ('original_lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='property_ops.lease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_ops_renewal',
            },
        ),
        migrations.CreateModel(
            name='RentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INVOICED', 'Invoiced'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedules', to='property_ops.lease')),
            ],
            options={
                'db_table': 'property_ops_rent_schedule',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_category', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profile', to='contacts.contact')),
            ],
            options={
                'db_table': 'property_ops_vendor',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING_FOR_PARTS', 'Waiting for parts'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='property_ops.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='inventory.property')),
                ('reported_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to='contacts.contact')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='inventory.unit')),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='property_ops.vendor')),
            ],
            options={
                'db_table': 'property_ops_maintenance_request',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('maintenance_request', models.ForeignKey(db_column='property_ops_maintenance_request_id', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='property_ops.maintenancerequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='property_ops.vendor')),
            ],
            options={
                'db_table': 'property_ops_work_order',
            },
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='property_ops_lease_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('deducted_amount__gte', 0), ('refunded_amount__gte', 0), ('amount__gte', django.db.models.expressions.CombinedExpression(models.F('refunded_amount'), '+', models.F('deducted_amount')))), name='property_ops_deposit_amounts_balance'),
        ),
        migrations.AddConstraint(
            model_name='renewal',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_end_date__gt', models.F('proposed_start_date'))), name='property_ops_renewal_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='renewal',
            constraint=models.CheckConstraint(condition=models.Q(('new_lease', models.F('original_lease')), _negated=True), name='property_ops_renewal_distinct_leases'),
        ),
        migrations.AddConstraint(
            model_name='rentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='property_ops_rent_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='property_ops_vendor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('reported_by_contact__isnull', False), ('reported_by_user__isnull', False), _connector='OR'), name='property_ops_maintenance_has_reporter'),
        ),
    ]
