# Generated by Django 5.1.4 on 2026-09-01 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('property_ops', '0002_lease_no_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentschedule',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_schedules', to='finance.invoice'),
        ),
    ]
