# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('crm', '0002_agent_location_point_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_steps', to='collaboration.template'),
        ),
        migrations.AddField(
            model_name='closingchecklistitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='collaboration.document'),
        ),
    ]
