# Generated by Django 5.1.4 on 2026-09-18 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_contacts_first_name_trgm_and_more'),
        ('crm', '0003_campaignstep_template_closingchecklistitem_document'),
        ('identity', '0005_user_must_change_password'),
        ('inventory', '0004_listing_inventory_listing_title_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_deal_property',
            },
        ),
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_deal_stage_history',
                'ordering': ['deal', '-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_possible_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sla_breached', 'sla_due_at'], name='crm_lead_sla_sweep_idx'),
        ),
        migrations.AddField(
            model_name='dealproperty',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_properties', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='dealproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_links', to='inventory.property'),
        ),
        migrations.AddField(
            model_name='dealproperty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_links', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.pipelinestage'),
        ),
        migrations.AddConstraint(
            model_name='dealproperty',
            constraint=models.UniqueConstraint(fields=('deal', 'property', 'unit'), name='crm_deal_property_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='dealproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('deal',), name='crm_deal_one_primary_property'),
        ),
        migrations.AddConstraint(
            model_name='dealstagehistory',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='crm_deal_stage_reason_not_blank'),
        ),
    ]
