# Generated by Django 5.1.4 on 2026-09-18 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_dealproperty_dealstagehistory_deal_stage_entered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_campaign_enrollment',
                'indexes': [models.Index(fields=['status', 'next_send_at'], name='crm_enrollment_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'lead'), name='crm_campaign_enrollment_uniq')],
            },
        ),
    ]
