"""Attach `identity_portal_profile` to the contact it represents (architecture.md §4).

Hand-written rather than autogenerated. The field is required — §4 specifies
`contact_id UUID FK contacts_contact UNIQUE`, and a portal profile with no contact is
meaningless — but `identity` is built before `contacts`, so `identity/0001` could not
reference the table. Adding a non-nullable column normally needs a default to backfill
existing rows; there are none, because nothing can create a portal profile until this
migration makes the model usable. Hence no default and `preserve_default=False`.

This is the general pattern for the build's forward references: declare the field in the
phase that introduces its *target*, and let the owning app pick up a small follow-up
migration. Django orders it correctly via the `dependencies` below.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("identity", "0002_seed_system_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalprofile",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portal_profile",
                to="contacts.contact",
            ),
            preserve_default=False,
        ),
    ]
