# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('identity', '0003_portalprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='collaboration.file'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='collaboration.file'),
        ),
    ]
