# Generated by Django 5.1.4 on 2026-09-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_company_logo_file_user_avatar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
