# Generated by Django 5.1.4 on 2026-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recordshare',
            index=models.Index(fields=['shared_with_user', 'entity_type'], name='identity_share_lookup_idx'),
        ),
    ]
